spring:
  application:
    name: TodoList
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_URI}
      database: todoList


server:
  port: ${PORT}

jwt:
  secret: ${JWT_SECRET}