spring:
  application:
    name: TodoList
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_URI}
      database: todoList


server:
  port: 3000

jwt:
  secret: ${JWT_SECRET:your-secret-key-here}